### ISSUE TITLE
Not sanitizing inputs

### ISSUE THREAD

**Issue by JericoFX** [n4n-0/nd-notify#1]
Hi n4n awesome script, but your code doest not check for weird inputs so i can send some weird stuff like h1, h4, img, here i can show you the code running in the browser and passing an image as data

https://jsfiddle.net/weqpLhbr/11/

**Comment by n4n-0** [comment]
Thanks for the feedback I will fix that issue soon.

**Comment by JericoFX** [comment]
i create a PR, maybe you can check it
